---
- name: 'create config dir'
  become_user: '{{ user.name }}'
  file:
    dest: '{{ user.config_dir }}'
    state: 'directory'

- name: 'remove old user-dirs.dirs file'
  file:
    dest: '{{ user.config_dir }}/user-dirs.dirs'
    state: absent

- name: 'copy user-dirs dirs config'
  become_user: '{{ user.name }}'
  copy:
    src: '{{ role_path }}/files/user-dirs.dirs'
    dest: '{{ user.config_dir }}/user-dirs.dirs'

- name: 'remove old user-dirs.locale file'
  file:
    dest: '{{ user.config_dir }}/user-dirs.locale'
    state: absent

- name: 'copy user-dirs locale config'
  become_user: '{{ user.name }}'
  copy:
    src: '{{ role_path }}/files/user-dirs.locale'
    dest: '{{ user.config_dir }}/user-dirs.locale'

- name: 'copy user aliases'
  become_user: '{{ user.name }}'
  file:
    src: '{{ role_path }}/files/aliases'
    dest: '{{ user.home_dir }}/.aliases'
    state: link
