---
- name: 'create config dir'
  become_user: '{{ user.name }}'
  file:
    dest: '{{ user.config_dir }}'
    state: 'directory'

- name: 'copy user-dirs dirs config'
  become_user: '{{ user.name }}'
  copy:
    src: '{{ role_path }}/files/user-dirs.dirs'
    dest: '{{ user.config_dir }}/user-dirs.dirs'

- name: 'copy user-dirs locale config'
  become_user: '{{ user.name }}'
  copy:
    src: '{{ role_path }}/files/user-dirs.locale'
    dest: '{{ user.config_dir }}/user-dirs.locale'

- name: 'copy user aliases'
  become_user: '{{ user.name }}'
  file:
    src: '{{ role_path }}/files/aliases'
    dest: '{{ user.home_dir }}/.aliases'
    state: link

- name: 'copy profile file'
  become_user: '{{ user.name }}'
  file:
    src: '{{ role_path }}/files/profile'
    dest: '{{ user.home_dir }}/.profile'
    state: link

- name: 'copy xprofile file'
  become_user: '{{ user.name }}'
  file:
    src: '{{ role_path }}/files/xprofile'
    dest: '{{ user.home_dir }}/.xprofile'
    state: link
