---
- name: 'Install bluetooth libraries and tools'
  pacman:
      name:
        - 'bluez'
        - 'bluez-libs'
        - 'bluez-utils'
        - 'blueman'
        - 'pulseaudio-bluetooth'
      state: present

- name: 'Enable bluetooth service'
  service:
    name: 'bluetooth.service'
    enabled: yes
