---
- name: 'Install Xorg packages'
  pacman:
    name: 
      - 'xorg-server'
      - 'xorg-xinit'
    state: present

- name: 'Install Xorg utilities'
  pacman:
    name: 
      - 'xorg-xev'
      - 'xorg-xinput'
    state: present

- name: 'Install LightDM'
  pacman:
    name: 
      - 'lightdm'
      - 'lightdm-gtk-greeter'
    state: present

- name: 'Enable LightDM'
  service:
    name: 'lightdm.service'
    enabled: yes
