---
- name: 'Installing ranger'
  pacman:
      name: 'ranger'

- name: 'Ranger config files'
  become_user: '{{ user.name }}'
  file:
    src: '{{ role_path }}/files/ranger'
    dest: '{{ user.config_dir }}/ranger'
    state: 'link'
  tags: 'dotfiles'
