---
- name: 'Installing termite'
  pacman:
    name: 'termite'

- name: 'Termite config file'
  become_user: '{{ user }}'
  file:
    src: '{{ role_path }}/files/termite'
    dest: '{{ user_config_dir }}/termite'
    state: 'link'
