---
- name: 'Install base packages'
  pacman:
    name:
      - 'python-pip'
      - 'xclip'
      - 'ntp'
    state: present

- name: 'Enable ntpd service'
  service:
    name: 'ntpd.service'
    enabled: yes
