---
- name: 'Installing nvim'
  pacman:
      name: 'neovim'

- name: 'Nvim config files'
  become_user: '{{ user }}'
  file:
    src: '{{ role_path }}/files/nvim'
    dest: '{{ user_config_dir }}/nvim'
    state: 'link'

- name: 'Installing python nvim plugin'
  pip:
    name: 'neovim'

#- name: 'Installing nvim plugins'
  #shell: 'nvim "+silent! PlugInstall!" +qall!'
